services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    # uncomment the following line to pull the image from docker hub
    # image: index.docker.io/catarak/p5.js-web-editor:latest
    # uncomment the following lines if you don't want export all of the variables
    # defined in your .env file for testing
    env_file:
    #   - "$PWD/.env.production"
      - "$PWD/.env"
    # environment:
    #   - API_URL
    #   - API_TOKEN
    #   - CORS_ALLOW_LOCALHOST
    #   - OP_404_SKETCH_ID
    #   - PORT
    #   - PREVIEW_PORT
    #   - EDITOR_URL
    #   - PREVIEW_URL
    #   - EXAMPLES_ENDPOINT
    #   - TRANSLATIONS_ENABLED
    #   - UPLOAD_LIMIT
    volumes:
      - .:/opt/node/app
      - /opt/node/app/node_modules
    ports:
      - '8000:8000'
      - '8002:8002'
